server:
  port: ${port:40100}
spring:
  application:
    name: xc-search-service
#xuecheng:
#  elasticsearch:
#    hostlist: ${eshostlist:192.168.0.102:9200} #多个结点中间用逗号分隔
#es http方式
elasticsearch:
  address: 192.168.0.102:9200
#  username: admin
#  password: admin
xuecheng:
  course:
    index: xc_course
    type: doc
    source_field: id,name,grade,mt,st,charge,valid,pic,qq,price,price_old,status,studymodel,teachmode,expires,pub_time,start_time,end_time
  media:
    index: xc_course_media
    type: doc
    source_field: courseid,media_id,media_url,teachplan_id,media_fileoriginalname